# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
- group: var-group

stages:
  - stage: Build
    displayName: "Build Docker Image"
    jobs:
      - job: Build
        displayName: "Build Docker Image"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # Checkout the repository
          - checkout: self
            displayName: "Checkout the repository"

          # # Print variables for debugging
          # - script: printenv
          #   displayName: "Print all environment variables"

          # Login to Docker Hub
          - script: |
              echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
            displayName: "Login to Docker Hub"

          # Build Docker image
          - script: |
              docker build -t dsmetaniak/bstg-webapp-image:latest .
            displayName: "Build Docker Image"

          # Push Docker image to Docker Hub
          - script: |
              docker push dsmetaniak/bstg-webapp-image:latest
            displayName: "Push Docker Image"

  - stage: Deploy
    displayName: "Deploy to Azure"
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: "Deploy to Azure App Service"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # Login to Azure and deploy Docker Image
          - task: AzureCLI@2
            inputs:
              azureSubscription: "aspnet-azure-connection"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az webapp config container set \
                  --name aspnet-service-name \
                  --resource-group aspnet-sample-rg \
                  --docker-custom-image-name dsmetaniak/bstg-webapp-image:latest \
                  --docker-registry-server-url https://index.docker.io/v1/





